[env:esp32_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

build_src_filter =
    +<MASTER_ESP32.cpp>
    -<SLAVE_STM32.cpp>


[env:stm32_slave]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink

upload_flags =
    -c
    set CPUTAPID 0x2ba01477

lib_deps =
    marcoschwartz/LiquidCrystal_I2C

build_src_filter =
    +<SLAVE_STM32.cpp>
    -<MASTER_ESP32.cpp>